name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install dependencies
        working-directory: desktop
        run: npm ci

      - name: Build portable executable
        working-directory: desktop
        run: npm run dist

      - name: Locate EXE
        id: exe
        shell: bash
        run: echo "path=$(ls desktop/dist/*.exe | head -n 1)" >> "$GITHUB_OUTPUT"

      - name: Upload Windows EXE
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ steps.exe.outputs.path }}
          asset_name: FOSCA-Pump-Driver-${{ github.event.release.tag_name }}-portable.exe
          asset_content_type: application/octet-stream

